name: DigitalOcean - Apply Terraform plan

on: repository_dispatch

jobs:
  apply-terraform:
    env:
      working-directory: ./tf
      DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
    name: Apply plan
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v1
      - name: Terraform init
        id: init
        run: terraform init
      - name: Terraform plan
        id: plan
        run: terraform plan -no-color
      - name: Terraform apply
        id: apply
        run: terraform apply -no-color -auto-approve -var-file="applications/digitalocean/env/dev.tfvars"
