name: DigitalOcean - Destroy Terraform plan

on: workflow_dispatch

jobs:
  apply-terraform:
    defaults:
      run:
        working-directory: "./tf"
    env:
      DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
    name: Destroy plan
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: ls -al
      - uses: hashicorp/setup-terraform@v1
      - name: Terraform init
        id: init
        run: terraform init
      - name: Terraform plan
        id: plan
        run: terraform plan -no-color
      - name: Terraform destroy
        id: destroy
        run: terraform destroy -no-color -auto-approve -var-file="applications/digitalocean/env/dev.tfvars" -var-file="applications/digitalocean/env/dev.tfvars"
